//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_Lý_Sách.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAO_DICH
    {
        public int MaGD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaSach { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTraDuKien { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
